name: add checklist template

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add PR template depending on label
      uses: PokaInc/pr-template-action@v1.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        template_dir: './../PULL_REQUEST_TEMPLATE/pull_request_template.md'
